deploy1: 
  ReplicaNumber: 1

  containers:
      containerPort: 8080
      image: 'quay.io/omer299/lab1'
      tag: 'chart_v1'

  service:
    servicePort: 8080
  argocd:
    syncwave:
      deployment: 5
      configmap: 1 

deploy2: 
  ReplicaNumber: 1

  containers:
      containerPort: 8080
      image: 'quay.io/omer299/lab1'
      tag: 'chart_v1'

  service:
      servicePort: 8080
  argocd:
    syncwave:
      deployment: 10
      configmap: 1

test: fail

github:
  user: omerh299
  token: empty-pass
  url: https://api.github.com/repos/omerh299/devopscourse/issues