deploy1: 
  ReplicaNumber: 1

  containers:
      containerPort: 8080
      image: 'ghcr.io/omerh299/helm/devopscourse'
      tag: '1.0.0'

  service:
      servicePort: 8080

deploy2: 
  ReplicaNumber: 1

  containers:
    containerPort: 8080
    image: 'ghcr.io/omerh299/helm/devopscourse'
    tag: '1.0.0'

  service:
    servicePort: 8080