ReplicaNumber: 3

containers:
  containerPort: 8080
  image: 'quay.io/omer299/lab1'
  tag: 'chart_v1'

service:
  servicePort: 8080

probes:
  readypath: /health/readiness
  readiness:
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1   
    failureThreshold: 3
  
  livepath: /health/liveliness
  liveness:
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1  
    failureThreshold: 3

volume:
  mount:
    path: /tmp/html